language: go
go_import_path: vighnesh.org/shodan
go:
  - 1.11.x
  - 1.12.x
  - master

env:
  - GO111MODULE=on

git:
  depth: 1

install: true

stages:
  - compile
  - test

jobs:
  include:
    - stage: test
      script: skip
