language: go
go_import_path: vighnesha.in/shodan
go:
  - 1.17.x
  - 1.18.x
  - master

env:
  - GO111MODULE=on

git:
  depth: 1

install: true

stages:
  - compile
  - test

jobs:
  include:
    - stage: test
      script: skip
